In [19]:
import os
import pandas as pd

In [20]:
data_path = '/tmp/openai-2024-03-20-17-43-59-690888/progress.csv'
data = pd.read_csv(data_path)
data = data.iloc[::]
data

,grad_norm,loss,loss_q0,loss_q1,loss_q2,loss_q3,mse,mse_q0,mse_q1,mse_q2,mse_q3,samples,step
0,3.150424,1.002269,1.002801,1.003187,1.002506,1.000583,1.002269,1.002801,1.003187,1.002506,1.000583,4,0
1,3.355632,0.900024,0.922740,0.876091,0.896212,0.905998,0.900024,0.922740,0.876091,0.896212,0.905998,44,10
2,2.908258,0.715696,0.782118,0.728637,0.687722,0.678495,0.715696,0.782118,0.728637,0.687722,0.678495,84,20
3,2.667654,0.527867,0.561515,0.509148,0.534639,0.518858,0.527867,0.561515,0.509148,0.534639,0.518858,124,30
4,2.343191,0.394923,0.438222,0.388881,0.367900,0.374283,0.394923,0.438222,0.388881,0.367900,0.374283,164,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1008,0.080201,0.003499,0.010276,0.001740,0.001312,0.000225,0.003499,0.010276,0.001740,0.001312,0.000225,40324,10080
1009,0.056016,0.003086,0.008413,0.001695,0.001482,0.000316,0.003086,0.008413,0.001695,0.001482,0.000316,40364,10090
1010,0.057541,0.003886,0.009436,0.001777,0.001286,0.000236,0.003886,0.009436,0.001777,0.001286,0.000236,40404,10100
1011,0.062220,0.002807,0.013110,0.001600,0.001197,0.000270,0.002807,0.013110,0.001600,0.001197,0.000270,40444,10110
1012,0.054216,0.002440,0.005574,0.002513,0.001691,0.000393,0.002440,0.005574,0.002513,0.001691,0.000393,40484,10120

In [21]:
column_name = 'loss'

# 해당 열에서 최솟값 찾기
min_value = data[column_name].min()

print(f"The minimum value in '{column_name}' is: {min_value}")

The minimum value in 'loss' is: 0.0012134576274547